name: Sync Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/meshtastic/firmware.git"
  # Required, token to authenticate bot, could use ${{ secrets.GITHUB_TOKEN }}
  # Over here, we use a PAT instead to authenticate workflow file changes.
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Optional, defaults to main
  UPSTREAM_BRANCH: "master"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "master"
  # Optional fetch arguments
  FETCH_ARGS: ""
  # Optional merge arguments
  MERGE_ARGS: ""
  # Optional push arguments
  PUSH_ARGS: ""
  # Optional toggle to spawn time logs (keeps action active)
  SPAWN_LOGS: "false" # "true" or "false"

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: "01 18 * * *"
  push:
    branches:
      - "main"

  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  syncUpstream_master:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}

  syncUpstream_develop:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: "develop"
          downstream_branch: "develop"
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}

  apply_flamingo_patch_master:
    runs-on: ubuntu-latest
    needs: syncUpstream_master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: "master"
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create temp branch
        run: git checkout -b temp

      - name: debug
        run: git remote -v

      - name: Cherry-pick commit
        run: git cherry-pick 8171aa4445be96b7051cd71c43afbe967eb89e0e

      - name: Force push temp branch to flamingo_updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force origin temp:flamingo_updated

  apply_flamingo_patch_dev:
    runs-on: ubuntu-latest
    needs: syncUpstream_develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: "develop"
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create temp branch
        run: git checkout -b temp

      - name: debug
        run: git remote -v

      - name: Cherry-pick commit
        run: git cherry-pick 8171aa4445be96b7051cd71c43afbe967eb89e0e

      - name: Force push temp branch to flamingo_updated_dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force origin temp:flamingo_updated_dev
